import Head from "next/head";

function HeadComponent() {
  return (
    <Head>
      <title>Anh Khoa</title>
      <meta name="description" content="Generated by Anh Khoa" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}

export default HeadComponent;
